using UnityEngine;

[SerializeField]
public enum enRulesetType
{
    IDONTKNOW = 11,
    BUMERANGGROUP = 21, LONLEYGROUP = 22, LONGSIDE = 23, SHORTSIDE = 24,
    ADJACENT = 31, CORNER = 32, OPPOSITE = 33,
    MIN2AWAY = 41, NOTADJACENTNOTOPPOSITE = 42
}
