public enum enRulesetType
{
    NO_PREFERENCE = 11,
    BUMERANG_GROUP = 21, LONLEY_GROUP = 22, LONG_SIDE = 23, SHORT_SIDE = 24,
    ADJACENT = 31, AROUND_THE_CORNER = 32, OPPOSITE_SIDE = 33,
    MINIMUM_DISTANCE_2 = 41, NOT_ADJACENT_NOT_OPPOSITE_SIDE = 42, SAME_AS = 43,
    CONTRARY_OF = 51
}